---
- hosts: all
  tasks:
    - name: Creating a user named tasdik on the specified web server.
      user: 
        name: tasdik
        state: present
        shell: /bin/bash
        groups: admin
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: Copy .ssh/id_rsa from host box to the remote box for user tasdik
      become: true
      copy: 
        src: ~/.ssh/id_rsa.pub
        dest: /home/tasdik/.ssh/authorized_keys
        mode: 0600
        owner: tasdik
        group: tasdik
    
    - name: Enable a basic firewall
      become: yes
      shell: |
        ufw allow OpenSSH
        ufw enable